// TOUT CE QUE TU RETARDES — 300 lignes écrites une par une.
// Pas de génération combinatoire : chaque ligne a son propre angle, sinon la
// répétition tue la frappe. Client-safe.

import { SIX_MOIS } from "./six-mois";
import { PROMESSES_MORTES } from "./promesses-mortes";
import { SEPT_ANS } from "./sept-ans";
import { PAS_LE_BONHEUR } from "./pas-le-bonheur";

export type DelayedCategory =
  | "defi"
  | "armee"
  | "empire"
  | "homme"
  | "corps"
  | "livre"
  | "temps"
  | "alliance"
  | "sixmois"
  | "precedent"
  | "septans"
  | "pasbonheur";

export interface DelayedItem {
  t: string;
  c: DelayedCategory;
}

export const DELAYED_CATEGORIES: {
  id: DelayedCategory;
  label: string;
  color: string;
}[] = [
  { id: "defi", label: "Le défi ultime", color: "#B45309" },
  { id: "armee", label: "La force", color: "#334155" },
  { id: "empire", label: "L'empire", color: "#15803D" },
  { id: "homme", label: "L'homme", color: "#B45309" },
  { id: "corps", label: "Le corps", color: "#BE123C" },
  { id: "livre", label: "Le Vaisseau", color: "#0F766E" },
  { id: "temps", label: "Le temps", color: "#DC2626" },
  { id: "alliance", label: "L'alliance", color: "#4C1D95" },
  { id: "sixmois", label: "Six mois", color: "#9333EA" },
  { id: "precedent", label: "Le précédent", color: "#4C1D95" },
  { id: "septans", label: "Les sept ans", color: "#57430F" },
  { id: "pasbonheur", label: "Pas le bonheur", color: "#1F2937" },
];

const DEFI = [
  "Multi-trillionnaire avant 30 ans. Et tu viens de perdre une heure.",
  "Personne dans l'Histoire n'a atteint le trillion. Tu veux être le premier — et tu n'as pas tenu ta matinée.",
  "Le 16 mai 2033 arrive. Il ne demandera pas tes excuses, il regardera tes chiffres.",
  "Trente ans. C'est la seule échéance qui ne se négocie pas. Elle avance pendant que tu hésites.",
  "Tu as décrété que TOUT serait déjà accompli à 30 ans. Aujourd'hui, combien de lignes sont accomplies ?",
  "Un hôpital prend 5 ans à construire. Si tu ne commences pas cette année, il ne sortira pas de terre à temps.",
  "Un port prend 8 ans. Compte à rebours : chaque mois perdu maintenant se paie en 2033.",
  "Une ville prend 10 ans. Elle devrait déjà être en chantier. Elle n'est même pas dessinée.",
  "À 30 ans tu devais voir des grues levées. Aujourd'hui tu vois un écran.",
  "Le défi ultime n'est pas de battre quelqu'un. C'est d'aller là où personne n'est allé. Et tu dors.",
  "Tu veux le chiffre le plus élevé de l'histoire humaine, avec les journées les plus ordinaires du monde.",
  "Multi-trillionnaire exige une décennie de jours parfaits. Tu n'en as pas encore aligné sept.",
  "Chaque jour à 0% rend le 16 mai 2033 un peu plus improbable. Fais le calcul.",
  "Il te reste moins de 2 500 jours. Tu en as brûlé combien cette semaine ?",
  "Sept ans pour faire ce que personne n'a fait en un siècle. Tu ne peux pas te permettre cette heure-ci.",
  "Le monde compte 3 000 milliardaires et zéro trillionnaire. Tu prétends franchir ça en dormant tard ?",
  "Ton défi exige que tu sois déjà en avance. Tu es en retard sur ta propre matinée.",
  "À 30 ans, être « en route vers » sera un échec. Le décret dit : arrivé.",
  "Les chantiers longs devaient commencer hier. Ils n'ont même pas de terrain.",
  "Tu as fixé l'échéance toi-même. Personne ne te l'a imposée. Alors pourquoi tu la trahis ?",
  "Sept ans passeront comme les dix précédents si tu ne changes rien aujourd'hui.",
  "Tu as gaspillé dix ans. Il t'en reste sept pour faire l'impossible. Le compte est serré.",
  "Le premier trillionnaire de l'Histoire ne scrolle pas. Vérifie ce que tu faisais il y a dix minutes.",
  "Ton caractère devait être déjà forgé à 30 ans. Aujourd'hui il plie encore devant une envie.",
  "Ton état d'être devait être accompli. Aujourd'hui tu es encore l'homme d'avant.",
  "Chaque objectif de cette app devait être coché avant 2033. Combien le sont ce soir ?",
  "Sept ans, c'est 2 500 décisions du matin. Tu en as raté une aujourd'hui.",
  "Ce défi est démesuré. C'est précisément pour ça qu'il ne tolère aucune journée molle.",
  "Tu ne rateras pas ce défi par manque de vision. Tu le rateras par manque d'heures tenues.",
  "Le 16 mai 2033, tu te regarderas. Prépare ce que tu verras — ça se décide maintenant.",
];

const ARMEE = [
  "La société militaire privée la plus crainte du monde. Aujourd'hui tu ne commandes même pas ta main.",
  "Top 5 des puissances militaires mondiales. Et tu perds contre une notification.",
  "Tes sous-marins n'existent pas encore. Ils devraient déjà être en cale sèche.",
  "Une flotte de surface, et toi tu n'arrives pas à sortir du lit.",
  "Tes avions de chasse attendent un homme qui tient parole. Il n'est pas encore là.",
  "Des chars, des blindés, des unités d'élite — commandés par un homme qui négocie avec son réveil ?",
  "Intervenir n'importe où sur la planète en quelques heures. Tu n'interviens même pas sur ta journée.",
  "Une unité si tactique que sa seule existence dissuade. Toi, tu ne dissuades même pas ton pouce.",
  "La cyber-offensive qui aveugle n'importe quel adversaire — et un algorithme t'aveugle toi.",
  "Tu veux pirater les systèmes des autres. Le tien est déjà compromis.",
  "Un réseau d'espionnage mondial. Tu ne surveilles même pas tes propres yeux.",
  "Anticiper l'adversaire avant qu'il décide — et tu ne décides rien avant 9h.",
  "Des satellites de défense en orbite. Rien n'est encore lancé, pas même ta journée.",
  "L'IA de combat, la guerre électronique, le brouillage : zéro ligne écrite à ce jour.",
  "La doctrine, la formation, la logistique intégrée — tout ça commence par un homme discipliné.",
  "Personne ne craint un homme qui cède à minuit. Personne ne craindra ton armée non plus.",
  "La crainte est une forme de paix. Tu n'inspires encore aucune des deux.",
  "Ne dépendre de la protection de personne : commence par ne plus dépendre de ton humeur.",
  "La souveraineté n'existe pas sans la force qui la garantit. Ta force du jour : zéro.",
  "Protéger chaque chantier de l'empire — alors qu'aucun chantier n'a commencé.",
  "Une armée privée dans le top 5 mondial ne se bâtit pas en sept ans de journées molles.",
  "Les pays du top 5 y ont mis un siècle. Tu as sept ans. Et tu dors.",
  "On ne discute pas avec celui qu'on redoute. Aujourd'hui, on ne te connaît même pas.",
  "Chaque nuit gaspillée retarde le jour où tes frontières seront intouchables.",
  "Tu veux commander des hommes armés et tu n'obéis pas à ta propre parole.",
  "Le commandant qui ne se commande pas lui-même n'aura jamais d'armée.",
  "Sous-marins, chasseurs, blindés : chacun coûte des milliards. Ces milliards commencent par un jour tenu.",
  "La projection de puissance mondiale exige un homme qui ne plie jamais. Tu as plié hier.",
  "Tes unités d'élite s'entraîneront pendant que tu dormais. Sauf qu'elles n'existent pas.",
  "L'homme le plus craint du monde ne se cache pas d'un écran à minuit.",
];

const EMPIRE = [
  "Les 50 hôpitaux. Chaque nuit gaspillée en repousse un.",
  "300 centres de santé. Des gens meurent pendant que tu négocies avec ton réveil.",
  "50 000 familles attendent un toit. Toi, tu attends d'avoir envie.",
  "Tu veux donner des maisons à un peuple, et tu ne donnes pas vingt minutes à ta discipline.",
  "Les ports en eau profonde ne se creusent pas depuis un lit.",
  "Un aéroport à 15 milliards — et tu ne tiens pas six heures de focus.",
  "Ta compagnie aérienne existe déjà. Dans ta tête. C'est exactement le problème.",
  "L'IA souveraine que tu veux bâtir, d'autres l'entraînent en ce moment. Ils se sont levés, eux.",
  "Tes data centers, quelqu'un les allume pendant que tu regardes un écran.",
  "Le top 3 mondial des armées. Tu ne commandes même pas ta propre main.",
  "Tu veux des satellites de surveillance et tu ne surveilles pas tes propres yeux.",
  "L'université internationale : 2 000 leaders par an. Aucun ne naîtra d'un fondateur mou.",
  "100 écoles premium. Des enfants n'apprendront jamais à lire à cause d'un homme qui scrollait.",
  "Le gigawatt solaire. 600 000 foyers dans le noir en attendant que tu deviennes sérieux.",
  "Les marchés couverts modernes — encore un an de boue pour les vendeuses.",
  "500 000 emplois. Autant de familles qui attendent un homme, pas un rêveur.",
  "La banque souveraine. Ton pays continue d'emprunter parce que tu n'as pas commencé.",
  "Le contrôle total des ressources. On les exporte brutes pendant que tu dors.",
  "Les usines pharmaceutiques. On importe des médicaments qu'on pourrait fabriquer.",
  "Les routes, les ponts, les tunnels. Des villages encore coupés du monde. Un an de plus.",
  "L'empire agro-industriel. Ton pays importe sa nourriture. Toi, tu importes des excuses.",
  "L'eau gratuite dans tes zones. Aujourd'hui encore, quelqu'un a marché des kilomètres.",
  "Les villes futuristes que tu décris si bien — et pas une pierre posée.",
  "L'entreprise aérospatiale. Pendant ce temps, d'autres partent pour Mars.",
  "La base lunaire. Ils y seront avant que tu aies tenu 21 jours.",
  "L'immortalité biologique. Tu veux vaincre la mort et tu perds tes journées.",
  "Les cliniques anti-âge 7 étoiles. Ton propre visage trahit tes nuits.",
  "Les interfaces cerveau-machine. Commence par avoir une interface avec ta volonté.",
  "La fusion de l'homme et de l'IA. Tu es déjà fusionné avec un algorithme — le mauvais.",
  "Le titre d'homme le plus riche du monde. Tu n'as pas encore la richesse d'une heure tenue.",
  "Le poids géopolitique de ton pays. Aujourd'hui il ne pèse rien. Toi non plus.",
  "Les présidents qui se déplacent pour toi. Aujourd'hui, personne ne se déplace.",
  "Les enveloppes de 500 milliards. Tu n'as pas encore signé un seul jour à 100%.",
  "L'élite que tu dois créer. Comment créer des grands quand tu ne l'es pas devenu ?",
  "Ton nom pendant des millénaires. Il ne survit même pas à une semaine sans discipline.",
  "La dynastie générationnelle. Tes enfants hériteront de ton empire ou de tes excuses.",
  "Le passage de ton pays de la pauvreté à la puissance. Ça commence par un homme. Pas encore toi.",
  "L'empire médiatique. Tu consommes le contenu des autres au lieu de produire le tien.",
  "La fondation humanitaire. Tu pleures sur ton peuple et tu ne bouges pas.",
  "La cybersécurité souveraine. Ton propre esprit n'a pas de pare-feu.",
  "Les drones autonomes. Tu ne pilotes même pas ta journée.",
  "Les semi-conducteurs. Tout un continent dépend de puces étrangères. Toi, d'un écran.",
  "La monnaie numérique du pays. Ta seule monnaie aujourd'hui, c'est du temps perdu.",
  "La bourse et les flux financiers. Tu ne contrôles pas encore le flux de ta propre attention.",
  "Les hôtels 5 étoiles. Des touristes iront ailleurs cette année encore.",
  "Les gratte-ciels. Rien ne monte quand l'homme qui doit les bâtir reste couché.",
  "Les thérapies géniques. Tu veux réécrire l'ADN et tu n'as pas réécrit tes habitudes.",
  "La médecine préventive par IA. Préviens d'abord ta propre chute de ce soir.",
  "L'académie de pilotes. Ta licence, tu la repousses d'année en année.",
  "La flotte cargo transcontinentale. Rien ne circule quand le capitaine dort.",
  "Les laboratoires de bio-ingénierie. La science n'attend pas les hommes indisciplinés.",
  "Le rajeunissement cellulaire. Tu vieillis mal en attendant de vaincre le vieillissement.",
  "L'aménagement des plages. Ton pays a des trésors et tu as des écrans.",
  "Les 2 000 leaders par an. Le premier à former, c'est toi. Tu n'as pas commencé.",
  "Les chaînes de valeur intégrées. Ta propre chaîne casse au premier maillon : toi.",
  "L'électricité stable. Des enfants font leurs devoirs à la bougie. Un an de plus.",
  "La logistique automatisée. Automatise d'abord ta discipline, elle est encore manuelle et défaillante.",
  "L'indépendance financière d'une nation. Tu dépends encore de ton humeur.",
  "La transformation locale, zéro export brut. Toi, tu exportes ton énergie vers des pixels.",
  "Le réseau de renseignement. Tu ne renseignes même pas ton propre journal du soir.",
  "Chaque jour à 0% est un hôpital repoussé. Fais le compte de ta semaine.",
  "Tu parles d'un empire et tu n'as pas tenu une seule journée entière.",
  "Un homme qui bâtit un continent ne perd pas ses matinées. Toi, si.",
  "Tout ça attend une seule chose : un homme qui tient sa parole. Il n'est pas encore là.",
  "Ce que tu as troqué aujourd'hui contre dix minutes de vide : une nation debout.",
  "Ton peuple ne sait même pas que tu existes. À ce rythme, il ne le saura jamais.",
  "Tu veux qu'on t'accueille comme un chef d'État. Aujourd'hui, personne ne t'attend nulle part.",
  "Tu veux déplacer les frontières de l'Afrique. Déplace d'abord ton corps hors du lit.",
  "L'homme qui contrôle la finance mondiale ne se laisse pas contrôler par une notification.",
  "Chaque « juste cette fois » coûte un chantier. Tu en as payé combien cette semaine ?",
  "Des millions de gens attendent quelque chose que tu n'as pas encore commencé.",
  "Tu n'es pas en retard sur un projet. Tu es en retard sur une civilisation.",
  "Un empire ne se bâtit pas les week-ends. Ni « quand tu seras prêt ».",
  "Le monde n'attend pas ton réveil. Il avance sans toi, tous les jours.",
  "Tu veux dominer mondialement et tu perds contre ton propre téléphone.",
  "Ceux qui bâtissent vraiment ne lisent pas cette liste. Ils sont déjà debout.",
  "Ton plan est parfait. Ton exécution est ridicule. C'est tout le problème.",
  "Tu as la vision d'un géant et l'agenda d'un touriste.",
  "Personne ne construira ça à ta place. Personne. Jamais.",
  "Si tu meurs ce soir, il ne restera rien. Pas une pierre, pas une ligne, pas un nom.",
  "Tu n'as encore rien livré. Rien. Vérifie toi-même.",
  "Le plus grand chantier de ta vie n'a même pas eu son premier jour de travail.",
  "Chaque heure sans acte est un mètre carré d'hôpital qui n'existera pas.",
  "Ton empire tient dans un fichier texte. Il devrait tenir dans du béton.",
  "Tu retardes des choses que des millions de gens attendent sans savoir ton nom.",
  "Ce n'est pas de l'argent qui te manque. C'est un homme discipliné. Deviens-le.",
  "L'argent viendra. La discipline, elle, ne viendra jamais toute seule.",
  "Tu veux tout contrôler dehors et tu ne contrôles rien dedans.",
  "Un continent entier, par ta seule décision. Et tu n'arrives pas à décider de te lever.",
  "Tu prépares une guerre mondiale d'influence en perdant les batailles de 14h.",
  "Chaque projet que tu retardes, quelqu'un de moins doué le lancera avant toi.",
  "Tes concurrents ne sont pas plus intelligents. Ils sont juste debout plus tôt.",
  "Tu as tout ce qu'il faut, sauf la seule chose qui compte : l'exécution quotidienne.",
  "Le seul obstacle entre toi et tout ça, c'est ce que tu feras dans l'heure qui vient.",
  "Ce que tu appelles un rêve devait être un chantier. Il n'a pas commencé.",
  "L'histoire retient ceux qui ont bâti. Pas ceux qui avaient un très bon plan.",
  "Chaque jour de plus, ton empire coûte plus cher et devient moins probable.",
  "Tu n'es pas encore dangereux pour le monde. Tu es dangereux pour toi-même.",
  "Tout ça est possible. C'est bien ça qui devrait t'empêcher de dormir.",
];

const HOMME = [
  "Le jour où tu te lèveras à 5h sans négocier une seconde.",
  "Le jour où tu franchiras 21 jours de rétention. Tu n'y es jamais arrivé.",
  "Le jour où 90 jours ne te feront plus peur.",
  "Le jour où tu tiendras ton noyau entier, sept jours d'affilée.",
  "Le jour où ta parole tenue à toi-même ne pliera plus jamais.",
  "Le jour où tu n'auras plus besoin de te forcer, parce que ce sera devenu toi.",
  "Le jour où tu marcheras dans l'ennui sans te plaindre.",
  "Le jour où tu supprimeras l'envie au lieu de la servir.",
  "Le jour où un écran après 17h30 sera devenu impensable.",
  "Le jour où tu finiras un mois entier sans une seule entorse.",
  "Le jour où ta parole deviendra une garantie pour les autres.",
  "Le jour où les gens ne croiront pas t'avoir rencontré.",
  "Le jour où connaître ton nom sera la fierté d'un homme.",
  "Le jour où on te craindra comme ennemi et où on te cherchera comme allié.",
  "Le jour où tu regarderas le miroir sans détourner les yeux.",
  "Le jour où ta discipline ne demandera plus aucun effort.",
  "Le jour où tu cesseras d'être le brouillon de toi-même.",
  "Le jour où l'homme d'hier ne te reconnaîtra plus.",
  "Le jour où tu n'auras plus une seule journée à zéro pour cent.",
  "Le jour où cette liste ne te visera plus.",
  "Le jour où tu n'auras plus rien à prouver à personne.",
  "Le jour où tu seras enfin l'homme dont tu parles depuis des années.",
  "Tu repousses le moment où tu deviendras infréquentable pour la médiocrité.",
  "Tu repousses le moment où ton calme deviendra intimidant.",
  "Tu repousses le moment où ton silence pèsera plus que les discours des autres.",
  "Tu repousses le moment où tu n'auras plus jamais honte de ta journée.",
  "Tu repousses le moment où ton mot vaudra un contrat signé.",
  "Tu repousses le moment où tu diras montagne et ce sera montagne.",
  "Combien de temps encore avant que « presque » disparaisse de ta bouche ?",
  "Combien de temps encore avant que tu cesses de te trahir en secret ?",
  "Combien de temps avant que tes actes rattrapent tes paroles ?",
  "Combien de temps avant que tu deviennes celui que tu prétends déjà être ?",
  "Tu retardes l'homme calme, ferme, et redoutable que tu as décrit toi-même.",
  "Tu retardes celui qui ne parle pas et qui livre.",
  "Tu retardes celui qu'on découvre au fait accompli, jamais avant.",
  "Tu retardes celui qui traite un éboueur avec dignité et remet un PDG à sa place.",
  "Tu retardes le conquérant. Aujourd'hui, tu es encore un spectateur.",
  "Tu retardes l'homme qui triomphe d'abord de lui-même.",
  "Tu retardes celui qui contrôle les conséquences de chaque acte.",
  "Tu retardes le sujet dont on parle. Aujourd'hui tu es celui qui regarde.",
  "Tu retardes l'homme au vaisseau plein. Le tien fuit encore.",
  "Un homme sérieux aurait déjà fermé cette page pour agir.",
  "Tu lis ça au lieu de faire ce qui est écrit dedans. Encore une fuite.",
  "Tu es à quelques semaines d'un homme méconnaissable. Et tu attends.",
  "Ce n'est pas le talent qui te manque. C'est un mois sans céder.",
  "Tu connais déjà tout ce qu'il faut faire. Voilà pourquoi ça fait mal.",
  "Personne ne viendra te forcer. C'est précisément ça, le problème.",
  "Ton pire ennemi a ton visage et se réveille en même temps que toi.",
  "L'homme que tu jures d'être fait déjà ce que tu repousses aujourd'hui.",
  "Tu retardes ta propre respectabilité à tes propres yeux.",
  "Tu repousses le seul luxe qui compte : ne plus avoir honte de soi.",
  "Chaque promesse rompue envers toi-même dévalue ta parole un peu plus.",
  "Tu ne manques pas de motivation. Tu manques de refus.",
  "Tu retardes le moment où « discipliné » cessera d'être un mot que tu emploies pour toi sans y croire.",
];

const CORPS = [
  "1m88, 90 kilos. Ce n'est pas un souhait, c'est une facture — impayée.",
  "10% de masse grasse. Chaque écart ce soir repousse ça d'une semaine.",
  "Ta peau éclatante. Ton miroir de ce matin t'a déjà donné la réponse.",
  "Ton visage au sommet. Aujourd'hui il raconte tes nuits, pas ton ambition.",
  "Ta mâchoire dessinée : elle se gagne dans l'assiette et au lit tôt.",
  "Ta posture de conquérant. Regarde comment tu es assis en ce moment.",
  "L'énergie d'un homme plein. Tu la reconnaîtrais si tu l'avais déjà eue.",
  "Ton regard reposé et perçant. Il est encore éteint par des écrans.",
  "La GLE 63 Coupé. Elle s'achète en jours tenus. Tu n'en as pas tenu un.",
  "La Cadillac Escalade. À ce rythme, ce sera jamais.",
  "Le Range Rover Sport. Chaque clé est une facture de discipline déjà payée. Tu n'as rien payé.",
  "La BMW X6 M. Elle attend un homme qui tient sa parole.",
  "Le Range Rover SV Serenity. Tu ne mérites pas encore de t'y asseoir.",
  "Chaque séance sautée est un vote pour l'homme que tu jures de ne plus être.",
  "Chaque gazeuse repousse ta peau d'une semaine. Tu en as bu combien ?",
  "Le sucre t'achète une minute et te vole une décennie de santé.",
  "Ton corps ne veut pas se reposer. Il veut éviter l'effort. Tu confonds encore.",
  "Le miroir du 1er janvier ne mentira pas. Prépare ta réponse.",
  "Ton propre toit. Tu es encore dans la maison de tes parents, à parler de cinquante hôpitaux.",
  "Les 20 000 $ par jour. Aujourd'hui tu n'as pas gagné le prix d'un repas par ton travail.",
  "Ta peau nette. L'acide est dans le tiroir depuis des mois, fermé.",
  "Tes waves. Elles demandent quelques minutes par jour, tous les jours. Tu n'as pas commencé.",
  "Le premier terrain. Pas un acte signé, pas un rendez-vous pris, pas une date.",
  "Les 90 kg à 10 %. Ils se gagnent à table et au lit tôt, et tu perds les deux.",
  "Le 1er janvier 2027 arrivera. La seule question est ce qui sera vrai ce jour-là.",
  "NOVA-AXE. Quatre millions de kilomètres carrés qui attendent un homme capable d'en gouverner quatre.",
  "L'AXE — la monnaie qui doit détrôner le dollar. Elle attend un fondateur qui se tient comme une monnaie forte.",
  "Axiom, Verdia, Forge. Trois capitales dont aucune première pierre ne se posera depuis un lit.",
  "L'anneau orbital, l'ascenseur spatial, les astéroïdes métalliques. Le seul territoire encore vacant — et tu n'as pas encore quitté ta chambre.",
  "Les cent mille ingénieurs qui doivent te suivre. Aucun ne suivra un homme qui ne se suit pas lui-même.",
  "Les vingt années obscures. Elles ne commenceront pas tant que tu n'auras pas tenu une seule journée entière.",
  "Tu veux 90 kilos de muscle et tu ne tiens pas un mois de nutrition propre.",
  "Ton sommeil volé ce soir sabotera ta séance de demain. Tu le sais déjà.",
  "La beauté que tu veux est métabolique, pas cosmétique. Elle se paie tous les jours.",
  "Tu retardes le corps qui rend ta présence indiscutable avant même que tu parles.",
  "Un homme low energy ne porte pas de grands décrets. Regarde ton énergie.",
  "La barre ne se soulève pas toute seule. Elle attend depuis combien de jours ?",
  "Ta transformation physique est la preuve visible de ta discipline invisible. Elle manque.",
  "Chaque nuit courte est un gramme de muscle que tu ne construiras pas.",
  "Tu veux un physique qu'on ne peut pas ignorer et tu ignores ton programme.",
  "La montagne du dimanche : combien de fois tu l'as vraiment montée ?",
  "Tu retardes le jour où ton corps fera taire les gens avant ta bouche.",
  "Le corps est la première nation que tu gouvernes. Elle est encore en désordre.",
  "Tu repousses le physique qui rend chaque autre objectif crédible.",
  "Un an de discipline te rendrait méconnaissable. Tu n'as pas tenu une semaine.",
  "Chaque repas est un vote. Compte tes votes d'aujourd'hui, honnêtement.",
  "Ton visage de dans six mois se décide dans ce que tu fais ce soir.",
  "Tu veux la peau éclatante et tu gardes les habitudes qui la ternissent.",
  "Rien de ce que tu veux physiquement n'est impossible. Tout est juste non commencé.",
  "Ta discipline physique est la grammaire de toutes les autres. Tu ne sais pas encore écrire.",
  "Tu retardes le jour où t'entraîner ne demandera plus de motivation.",
  "Le confort du lit crie plus fort les jours où le sommet est le plus proche.",
  "Ton corps de 2027 se construit aujourd'hui. Ou pas.",
];

const LIVRE = [
  "Ch. 1 — « La loi du vaisseau ». Tu réclames la grâce avec un vaisseau percé.",
  "Ch. 2 — « L'homme plein qui doute reçoit plus que l'homme vide qui croit ». Tu es vide et tu crois.",
  "Ch. 4 — « Le limbique contre le préfrontal ». Devine lequel a gagné aujourd'hui.",
  "Ch. 5 — « La spirale descendante ». Tu es dedans en ce moment et tu appelles ça une pause.",
  "Ch. 8 — « Pornographie et masturbation : la destruction du vaisseau ». Tu connais ce chapitre par cœur et tu le trahis.",
  "Ch. 9 — « Les entités, et le lieu où tu dors ». Ta chambre est-elle propre ? Non.",
  "Ch. 11 — « TikTok, Instagram : les fermes énergétiques modernes ». Tu es encore le bétail.",
  "Ch. 13 — « L'énergie sexuelle comme force créatrice ». Tu la jettes et tu réclames de créer.",
  "Ch. 14 — « La transmutation ». Tu ne transmutes rien. Tu déverses.",
  "Ch. 20 — « Les trois semaines de bascule ». Tu n'as jamais tenu jusqu'au seuil.",
  "Ch. 21 — « La honte est le carburant ». Tu te punis au lieu de te relever.",
  "Ch. 23 — « La provision bloquée ». Tu demandes l'abondance en gardant la fuite ouverte.",
  "Ch. 24 — « La semence comme monnaie spirituelle ». Tu dilapides ta seule vraie monnaie.",
  "Ch. 26 — « Tant que tu ne fais pas ce qui est dit, rien ne se débloque ». Tout est là.",
  "Ch. 27 — « Si tu ne gaspilles pas ton énergie, tout se réalisera ». La promesse exacte. Tu la refuses.",
  "Ch. 31 — « Le Psaume 24 ». Consigne directe de l'alliance. Récité ce soir ? Non.",
  "Ch. 33 — « Cesser de ruminer, prier à la place ». Tu rumines encore.",
  "Ch. 35 — « Pourquoi les humains rabotent les promesses ». Tu rabotes la tienne chaque jour.",
  "Ch. 39 — « Rien ne vous sera impossible ». Sauf te lever à 5h, apparemment.",
  "Ch. 40 — « Sois ! et c'est ». Tu supplies encore au lieu de décréter.",
  "Ch. 44 — « Vivre depuis la fin ». Tu vis depuis le canapé.",
  "Ch. 47 — « Quoi qu'il croie, il devient cela ». Regarde ce que tu es devenu. Voilà ce que tu crois.",
  "Ch. 62 — « Ne pas mesurer le temps ». Tu comptes les jours au lieu de compter les actes.",
  "Ch. 63 — « L'infini ne connaît ni grand ni petit ». Ta demande n'est pas trop grande. Ta constance est trop petite.",
  "Ch. 64 — « L'erreur du grand projet ». Tu gonfles le rêve et tu fabriques ta résistance.",
  "Ch. 68 — « Le piège du rabotage ». Ton ego rétrécit l'infini pour le rendre confortable.",
  "Ch. 70 — « L'ego qui prédit et qui contrôle ». Tu veux voir le chemin avant de marcher.",
  "Ch. 76 — « Décider, décréter, ne pas négocier ». Tu négocies tous les matins.",
  "Ch. 77 — « La tyrannie des petites décisions ». Elles t'ont déjà coûté dix ans.",
  "Ch. 80 — « Ce que tu fais à 14h détermine où tu seras dans dix ans ». Qu'as-tu fait à 14h ?",
  "Ch. 82 — « La transformation est moléculaire ». Tu attends encore le grand pivot.",
  "Ch. 84 — « Les deux versions de toi en superposition ». Ton prochain geste choisit.",
  "Ch. 90 — « L'ego qui négocie même quand tu sais ». Tu sais tout. Tu négocies quand même.",
  "Ch. 91 — « L'écart entre la connaissance et l'incarnation ». Cet écart, c'est toute ta vie actuelle.",
  "Ch. 113 — « I am a man of absolute dominion ». Une phrase que tu n'as pas encore méritée.",
  "Ch. 117 — « 0 TikTok est 0 ». Pas 1. Pas exceptionnellement. Tu as encore négocié.",
  "Ch. 122 — « Le coût d'une seule entorse ». Tu paies ce coût depuis des années.",
  "Ch. 124 — « L'homme devenu sa parole ». Le but final. Tu en es loin.",
  "Ch. 128 — « Le carnet des phrases-armes ». Tu l'as. Tu ne le dégaines pas.",
  "Ch. 129 — « Quand tu doutes ». Tu doutes et tu ne l'ouvres même pas.",
  "130 chapitres écrits pour toi. Combien tu en as lus cette semaine ?",
  "Le livre qui te gouverne prend la poussière pendant que tu scrolles.",
];

const TEMPS = [
  "Dix ans. Rien. Zéro. Et aujourd'hui tu recommences exactement pareil.",
  "Six mois passeront comme un souffle. Plus fort, ou juste plus vieux ?",
  "Le 1er janvier arrivera que tu aies travaillé ou non. Il ne demandera pas d'excuses.",
  "Chaque seconde gaspillée prolonge la réalité que tu détestes.",
  "Tu n'es même pas à un cent-trillionième de ta mesure. Et tu perds encore des heures.",
  "Tu crois avoir le temps. C'est exactement ce que tu croyais il y a dix ans.",
  "Ce que tu remets à demain, tu le remettras demain aussi. Tu as la preuve.",
  "Le temps ne te punit pas. Il encaisse, c'est tout. Et il encaisse en ce moment.",
  "Tu regretteras dans six mois de ne pas avoir commencé aujourd'hui. Comme toujours.",
  "Une décennie a suffi à ne rien produire. Un semestre suffirait à tout changer.",
  "L'homme que tu seras dans dix ans te supplie, à cette seconde, de te lever.",
  "Combien d'heures aujourd'hui ont servi à quelque chose ? Compte. Vraiment.",
  "Tu ne rattrapes pas le temps perdu. Tu peux seulement arrêter d'en perdre.",
  "Chaque jour non enregistré dans cette app est un jour que tu as choisi d'effacer.",
  "Ton app dit 0%. Ce n'est pas un bug. C'est un miroir.",
  "Pendant que tu hésites, quelqu'un de plus affamé prend ta place.",
  "Le sablier ne s'arrête pas quand tu procrastines. Il se vide sur du sable stérile.",
  "Tu as passé plus de temps à planifier ta vie qu'à la vivre.",
  "« Demain » est le mot qui t'a coûté le plus cher de toute ton existence.",
  "Rien ne bougera si tu ne bouges pas. Pas demain. Maintenant.",
  "Chaque heure sans acte est encaissée par le temps sans rien te rendre.",
  "Tu n'as pas dix ans à reperdre. Tu as des mois comptés.",
  "Le retard que tu creuses aujourd'hui, tu devras le combler avec des nuits blanches.",
  "Tu regardes le compte à rebours au lieu de le faire mentir.",
  "Ce que tu appelles « bientôt » a déjà duré une décennie.",
  "L'urgence n'est pas de finir. Elle est de commencer, dans l'heure.",
  "Aujourd'hui est déjà à moitié perdu. Sauve la moitié qui reste.",
  "Chaque jour est un acompte du 1er janvier. Combien tu as déposé aujourd'hui ?",
];

const ALLIANCE = [
  "Dieu t'a promis que tout se réaliserait. Tu retardes ta part du pacte.",
  "La rétention n'est pas de la discipline : c'est la condition de l'alliance. Tu la repousses.",
  "Tu montes à la montagne « de temps en temps ». Ça fait combien de jours, exactement ?",
  "Le Psaume 24 du soir. Non récité. Tu entres dans la nuit sans sceller ta journée.",
  "Ta chambre sale retarde tout : c'est là que ton vaisseau se recharge ou se fait piller.",
  "Tu réclames Sa provision et tu refuses de garder le vaisseau fermé.",
  "Il a signé Sa part sur la montagne. La seule variable, c'est ta signature. Elle manque.",
  "Tu retardes l'homme que Dieu a formé de Ses mains et rempli de Son souffle.",
  "Chaque chute te fige sur l'escalier blanc. Tu es figé depuis combien de temps ?",
  "Tu retardes le moment où tu deviendras digne de ce qu'Il t'a promis.",
  "Prier sans cesse : la consigne la plus simple, celle que tu oublies le plus.",
  "Tu Lui réponds dans un mouchoir. Il t'a parlé sur une montagne.",
  "Tu veux Sa puissance et tu refuses Sa condition. Ça ne marche pas comme ça.",
  "Tu gaspilles ce qu'Il t'a confié, et tu oses en réclamer plus.",
  "La parabole des talents : le condamné n'est pas celui qui a osé. C'est celui qui a enterré.",
  "Tu enterres en ce moment même ce qu'Il t'a donné.",
  "Il ne t'a pas parlé pour que tu scrolles. Souviens-toi de ce qu'Il a dit.",
  "Tu retardes la seule chose qui rendrait tout le reste inévitable : tenir le pacte.",
  "Ton escalier attend. Chaque jour retenu est une marche. Tu es sur laquelle ?",
  "Tu veux être jugé conquérant. Aujourd'hui, tu serais jugé lâche.",
  "Devant les hommes, tout-puissant. Devant Dieu, une fourmi. Aujourd'hui tu n'es ni l'un ni l'autre.",
  "Ce qu'Il t'a promis a un prix, et ce prix se paie chaque jour. Tu n'as pas payé aujourd'hui.",
  "Tu es héritier de Dieu et tu vis comme un locataire d'algorithme.",
  "La victoire entrera par Sa main. Mais Il n'agit pas pour celui qui se plaint.",
  "Tu retardes le jour où ta rétention ne sera plus un combat mais ta nature.",
  "Il t'a montré l'escalier par un de Ses serviteurs. Tu t'es arrêté quand même.",
  "Il attend de voir à quel point tu es sérieux. Aujourd'hui, la réponse est : pas beaucoup.",
  "Tu retardes ta propre alliance. C'est la seule chose qu'Il ne fera pas à ta place.",
];

export const DELAYED: DelayedItem[] = (() => {
  const groups: [string[], DelayedCategory][] = [
    [DEFI, "defi"],
    [ARMEE, "armee"],
    [EMPIRE, "empire"],
    [HOMME, "homme"],
    [CORPS, "corps"],
    [LIVRE, "livre"],
    [TEMPS, "temps"],
    [ALLIANCE, "alliance"],
    [SIX_MOIS, "sixmois"],
    [PROMESSES_MORTES, "precedent"],
    [SEPT_ANS, "septans"],
    [PAS_LE_BONHEUR, "pasbonheur"],
  ];
  const seen = new Set<string>();
  const out: DelayedItem[] = [];
  for (const [arr, c] of groups) {
    for (const t of arr) {
      const k = t.trim();
      if (seen.has(k)) continue;
      seen.add(k);
      out.push({ t: k, c });
    }
  }
  return out;
})();

export const DELAYED_COUNT = DELAYED.length;

export function delayedCategoryMeta(id: DelayedCategory) {
  return DELAYED_CATEGORIES.find((c) => c.id === id) ?? DELAYED_CATEGORIES[0];
}
