// THE MIRROR — English.
//
// Même contenu que miroir.ts + miroir-plus.ts, dans la langue où il écrit ses
// lignes les plus dures (FIRE, les déclarations, le test de la foi). Les
// phrases anglaises qui existaient déjà dans l'app sont reprises telles quelles,
// pas retraduites : ce sont ses mots.
//
// Client-safe.

import type { MiroirBloc } from "./miroir";

export const MIROIR_EN: MiroirBloc[] = [
  {
    id: "verite",
    titre: "What I am, right now",
    lignes: [
      "I am not a single one of the things I say I want to be.",
      "I am a chronic masturbator.",
      "I am a man who cannot concentrate.",
      "I am a dog on a leash. I am not a man of dominion.",
      "I am a coward.",
      "I am neither reliable nor trustworthy.",
      "I am small and weak. I could not defend anyone in the street, even if I wanted to.",
      "At 23, I am tired all the time.",
      "5'7\". 148 pounds. That is the real man.",
    ],
  },
  {
    id: "consentement",
    titre: "What I prove every second",
    lignes: [
      "I accept my current state. And every second, I prove it.",
      "I prove that I want to stay this height.",
      "I prove that I want to keep this body.",
      "I prove that I want to keep this face.",
      "I prove that I want to keep this charisma.",
      "I prove that I want to keep this voice.",
      "I prove that I want to keep this life.",
      "I never actually prove that I want what I say I want.",
      "Saying is not wanting. Wanting is proven, and the proof is an act.",
      "What I do is the only honest statement of what I want. The rest is noise.",
      "I don't need to ask myself what I want — I only need to look at what I do with my hours.",
      "My actual schedule is my actual list of goals.",
      "Every second is a vote. I vote to stay the same.",
      "Doing nothing is not neutral. It is signing.",
      "The man I will be in a year is already being chosen, second by second, by what I do now.",
    ],
  },
  {
    id: "membres",
    titre: "My limbs — what they actually serve",
    lignes: [
      "My hand builds nothing of what I say, think or plan. It serves to masturbate.",
      "My feet do not walk in glory. They walk in dust, and they serve to carry me into my room to jerk off.",
      "My eyes do not look at the accomplishment of what I planned. They look at porn.",
      "This body, He formed with His own hands — and this is the use I make of it.",
      "That is the real use of what He entrusted to me. Not the dreamed use: the real one.",
      "A coward. A piece of shit. Unworthy of God, of His trust, and of His blessings.",
    ],
  },
  {
    id: "porno",
    titre: "Porn — what the act actually proves",
    lignes: [
      "I say I want, as a man, access to the women I want. To the most beautiful ones.",
      "What my acts prove I want is something else: to jerk off like a coward, a piece of shit, nothing at all.",
      "To watch another man fuck the woman who is the object of my desire. And to pay for that show with my energy.",
      "That is not a man's desire. That is a spectator's desire.",
      "I do not take his place. I watch him take it, and I pay to watch.",
      "Then I put music on and dream of being great. I call myself a man of dominion. Son of God.",
      "A man of dominion who just watched another man take his place. Same hour. Same hand.",
      "That is the whole loop: the porn, the hand, the music, the daydream of greatness. And nothing at the end.",
      "None of the women I claim to want will ever know I exist, because I spend the time that should build me watching others.",
    ],
  },
  {
    id: "vouloir",
    titre: "I don't want them — I want to want them",
    lignes: [
      "If I really wanted these things, I would have done what was necessary to see them.",
      "If I wanted the cars, I would have done what was necessary.",
      "If I wanted the buildings, the companies, the glory, the fame, I would have done what was necessary.",
      "I don't want them. I want to want them.",
      "What I love is the feeling of wanting. It costs nothing, demands no act, and gives almost the same pleasure.",
      "A desire I have not paid for is not a desire. It is entertainment.",
      "A man who truly wants something is recognized by what he sacrificed. I have sacrificed nothing.",
      "I confuse the emotion of wanting with the decision of doing.",
      "As long as wanting stays free, I will keep wanting, and I will never have anything.",
    ],
  },
  {
    id: "achats",
    titre: "What I bought and never opened",
    lignes: [
      "I ordered the exfoliating acid on Amazon. It is in my room. I have not used it in months.",
      "I bought the pomades for waves, the durag. They are there. Unused.",
      "I bought the whitening strips — thirty minutes on the teeth. Never opened.",
      "Buying gave me the feeling of acting. That is exactly where the action stopped.",
      "These are not objects sitting in a room. They are my will, my discipline and my acts, sitting on a shelf.",
      "I am not even missing the product. It is already paid for, already there, one meter away from me.",
      "My teeth are yellow by choice, not by lack. Thirty minutes stand between me and clean teeth, and they are free.",
      "Between me and clear skin there is no money, no time, no knowledge. There is only the gesture.",
    ],
  },
  {
    id: "question",
    titre: "The question — and the real answer",
    lignes: [
      "Does yesterday represent what I want?",
      "Does last week represent what I want?",
      "Does today represent what I want?",
      "Does this very minute represent what I want?",
      "The answer is no. And yet it is what I chose — hour after hour.",
      "Therefore: I do not want clear skin. I do not want superhuman accomplishments. I want none of it.",
      "What I want is what I do. There is no other definition, and no court will accept another one.",
      "The only way to change my answer is to change the hour that is coming. Not the year: the hour.",
    ],
  },
  {
    id: "limites",
    titre: "I don't even fill this small life",
    lignes: [
      "I am not trying to find my limits. I don't even fill this small, mediocre life I'm already in.",
      "I am not even at the edge of what my current life already allows.",
      "I talk about surpassing the human, and I don't even occupy the twenty-four hours I have.",
      "I touch no ceiling. I have never come close to a single ceiling.",
      "Nobody can know what I'm capable of: I have never carried anything through to the end, not even something small.",
      "My mediocrity itself is not filled. It is half empty.",
      "I don't know my limits because I have never made it all the way to them.",
      "I dream of the boundless from a bed I haven't even made.",
      "Before wanting to exceed my limits, I would first have to reach the edge of this small space.",
      "The little I have, I do not use. And I dare to ask for more.",
    ],
  },
  {
    id: "preuves",
    titre: "The evidence — there is none",
    lignes: [
      "There exists no evidence of my intelligence.",
      "There exists no evidence of my work.",
      "There exists no evidence of my greatness.",
      "Eight years. Not one project in progress. Not one.",
      "I have accomplished none of my goals. Not one.",
      "Nobody — not God, not an angel, not an invisible observer — could guess my goals by watching me live. It is impossible.",
      "My financial situation is the exact measure of my mediocrity.",
      "My body, my face, my charisma: the same measure.",
    ],
  },
  {
    id: "parole",
    titre: "My word — every goal betrayed",
    lignes: [
      "I have never held a single day of discipline. Not one.",
      "Every goal I set for myself, I betrayed.",
      "Waking at 5 a.m.: betrayed.",
      "Retention: betrayed.",
      "Zero TikTok: I reinstall the app and reactivate the account every single day.",
      "I go on X like a dog.",
      "I cannot put my ass in a chair and work four hours straight.",
      "I cannot stop the maladaptive daydreaming.",
      "I do not go to the mountain.",
      "I desperately seek the attention of girls.",
      "I do not hold my meditation hours.",
      "I do not hold my deep work sessions.",
      "I want to make money on YouTube and I don't even publish a single fucking video. That is the whole case file.",
    ],
  },
  {
    id: "reverie",
    titre: "The scenes I replay instead of living",
    lignes: [
      "I endlessly replay the same scenes: the interview, the success already achieved, the wisdom I dispense.",
      "In those scenes, I offer a wisdom and an intelligence that simply do not exist.",
      "I consume the result in my imagination — and afterwards I am no longer hungry enough to build it.",
      "And if I keep going like this, it will surely never happen. At 200%.",
      "I do not refuse to stop the compulsive daydreaming: I do not even decide to stop it.",
      "I do not decide to stop imagining, simply to keep my mind calm and do the work.",
      "Dreaming the interview costs me the interview.",
      "Every replayed scene is an advance drawn on a glory I will never pay for.",
      "The man in my mental scenes did the work. I just watch him do it.",
    ],
  },
  {
    id: "apparence",
    titre: "The face and the body, no filter",
    lignes: [
      "5'7\". 148 pounds. Weak. That is the real man, measured.",
      "An unwashed face, covered in acne.",
      "Yellow teeth.",
      "No fragrance. Nothing that stays when I leave.",
      "No charisma. No presence.",
      "Below average on just about everything that shows.",
      "Invisible. Insignificant. Repulsive.",
      "I walk through a room without anyone noticing, and that is exactly what I built.",
      "None of this is an accident. Every line is a gesture I did not make.",
    ],
  },
  {
    id: "corps",
    titre: "The body — five years for nothing",
    lignes: [
      "Five years in the gym, and I look like shit.",
      "I do not respect the program.",
      "I do not lift hard.",
      "I have no discipline on nutrition after the session.",
      "Every day, I go back to soda.",
      "Gym goal: failed. Five years of proof.",
    ],
  },
  {
    id: "ecart",
    titre: "The gap between the dream and the act",
    lignes: [
      "I dream of trillions and I don't even do what a man earning a thousand dollars does.",
      "I dream of millions on YouTube without producing the effort of those who make a thousand.",
      "I want to publish on the App Store for billions, and I spend my Claude credits — a 200-dollar plan — to go on X.",
      "I look for the easy things. And even those, I do not do.",
      "And then I allow myself to criticize.",
      "I always look for a way out of the work I know is necessary to my evolution.",
      "As if YouTube would create the videos for me, publish them for me, and pay me.",
    ],
  },
  {
    id: "outils",
    titre: "The tools I abandoned",
    lignes: [
      "I printed a sheet to check off my goals. I have not used it a single time.",
      "I set up an automatic email system. I do not open them.",
      "I have the books. I do not read them.",
      "I do absolutely nothing of what I say I am going to do.",
    ],
  },
  {
    id: "evitement",
    titre: "Avoidance by building",
    lignes: [
      "I build the tools so I don't have to use them.",
      "I built an app, a 587-page book, 2,000 quotes, an automatic email system. I have opened none of those emails.",
      "Adding one more feature gives me the sensation of progress. It is the sophisticated version of procrastination.",
      "The moment a system is ready to be followed, I would rather modify it than follow it.",
      "I spend more time adjusting the counter than doing the thing it counts.",
      "Every new idea arrives exactly when the previous one needs to be executed.",
      "I ask to have a discipline system built for me, and I don't have the discipline to use it.",
      "Preparing is still a way of not starting.",
    ],
  },
  {
    id: "lucidite",
    titre: "What I already know — and it changes nothing",
    lignes: [
      "I know all of this. I wrote it myself.",
      "My problem is not ignorance. I have nothing left to learn before acting.",
      "I am missing no information. I am missing no tool. I am missing no system.",
      "I know the law of the vessel by heart — I wrote it — and I do not apply it.",
      "Being lucid about my mediocrity does not correct it. It only makes it more shameful.",
      "Understanding is not doing. Writing is not doing. Reading is not doing.",
      "Every day I change nothing is a vote for the man I already am.",
    ],
  },
  {
    id: "jugement-divin",
    titre: "What the LORD condemned — and what I practice",
    lignes: [
      "The LORD did not condemn only the ones people point at — homosexuality, sorcery, reading the stars.",
      "\"But the cowardly, the unbelieving, the vile, the murderers, the sexually immoral, those who practice magic arts, the idolaters and all liars — their place will be in the fiery lake of burning sulfur.\" (Revelation 21:8)",
      "The cowardly are named FIRST. Before the murderers. Before the idolaters.",
      "I am on that list, and I am at the top of it.",
      "\"Do not be deceived: neither the sexually immoral nor idolaters… will inherit the kingdom of God.\" (1 Corinthians 6:9-10)",
      "\"The acts of the flesh are obvious: sexual immorality, impurity, debauchery… those who live like this will not inherit the kingdom of God.\" (Galatians 5:19-21)",
      "The slave of his flesh, the slave of his hand, the man led by his desire: condemned too. By name.",
      "This is not a tolerated weakness filed away somewhere else. This is what bars entry to the Kingdom.",
      "I reassure myself by comparing my sin to other people's. God does not run that ranking.",
      "I am not less condemned because my fault is ordinary, hidden, and hurts no one but me.",
      "I am not \"a good guy with a small problem\". I am on the list, on the first line.",
      "And I know it. And I will do it again tonight.",
    ],
  },
  {
    id: "temps",
    titre: "What happens if nothing changes",
    lignes: [
      "I waste my time every day, and I still expect to reach my goals.",
      "I treat tomorrow as the wonderful day when my mediocrity disappears on its own.",
      "I keep dreaming while the years pass and prove me wrong.",
      "And it will be like this tomorrow.",
      "Like this in a week.",
      "Like this in a month. In six months.",
      "Like this in a year. In two years.",
      "Next month will be exactly the same.",
      "The end of the year will be exactly the same.",
      "The year after too. Then 25. Then 30. Then 40.",
      "As long as I stay like this, nothing will change, and the years will keep passing.",
    ],
  },

  // ——— Section II : ses phrases, retournées ———
  {
    id: "refus",
    titre: "The man I refuse to be — and am exactly",
    lignes: [
      "The man I refuse to be is, word for word, the man I am.",
      "A compulsive masturbator. A man with no control. A dog on a leash led by lust. That is me.",
      "A coward. A fucking nobody. An average guy — plain, replaceable, forgettable. That is me.",
      "A dreamer who jerks off on his own future instead of building it. That is me.",
      "An emperor in thought, a slave in practice. That is me.",
      "I claim I will move the borders of Africa, and I don't even control my hand.",
      "I want to dominate markets and nations, and a notification dominates me.",
      "The one people talk about? Nobody talks about me. Nobody knows I exist.",
      "God spoke to me on a mountain — and I answer Him into a tissue.",
      "I waste what He entrusted to me, and I dare to ask for more.",
      "Ten years. Nothing. Zero. And I think I'm in a hurry today.",
      "I am not a king. I am a dog dreaming of being king.",
    ],
  },
  {
    id: "phrases-retournees",
    titre: "My own lines, turned against me",
    lignes: [
      "\"I don't go on TikTok.\" I reinstall the app and reactivate the account every day.",
      "\"I am the one people talk about, and who never fades.\" Nobody talks about me.",
      "\"I am the one who does all of this. Not in 5 minutes. NOW.\" I did it on none of the days I said it.",
      "\"Every action has consequences.\" I live as if none did.",
      "\"Every action is an exchange. Calculate what you take and what you give.\" I have never once done the math.",
      "\"Every action is a pact. Who did you just sign with?\" I sign every day, and I know with whom.",
      "\"Every yes is a thousand no.\" I say yes to everything that destroys me.",
      "\"Only God and you can stop you.\" God is not stopping me. So there is only me left.",
      "\"No alibi is left to you. Only you.\" I have no one left to blame, and I still don't act.",
      "\"God kept His word. Now keep yours.\" He kept His. I have not kept mine for a single day.",
      "\"A dog with a dream is still a dog.\" I am the dog. The dream is intact; I am not.",
      "\"Ten years. Zero receipts.\" That is my line. I wrote it about myself.",
      "\"You'll either be the story or the audience.\" I am the audience. I watch others be the story.",
      "\"Nobody is coming. That's the whole point.\" Nobody came. Nobody will.",
      "\"Let Him judge me for the arrogance of the power He gave me — never for having buried it.\" I buried it. That is exactly the judgment I claimed to refuse.",
      "\"Let Him judge me a conqueror, never a coward.\" He will judge me a coward, and He will have the receipts.",
      "\"My body, He formed it with His own hands.\" And this is what I do with it.",
      "\"I refuse to be a coward, a masturbator, a submissive man.\" I am all three, today.",
      "\"If you really want to build them, respect your hand.\" I do not respect it. So I do not want to build them.",
      "\"If you really want to see them, respect your eyes.\" I do not respect them. So I do not want to see them.",
      "\"There is no third door.\" I have spent eight years looking for one.",
      "\"Pray without ceasing.\" I do not pray.",
      "\"God is my source, His supply is unlimited, nothing is impossible to God.\" I ask Him for nothing, and I do nothing.",
      "\"Unshakable. Boundless. Faithful.\" I bend every day, I produce nothing, and I hold nothing.",
      "\"I don't talk, I don't debate, I don't opine. I DO. I ACT.\" I talk, I debate, I opine. I do nothing.",
      "\"I am God's heir. I refuse to be a fucking nobody.\" Today, I am exactly what I refuse.",
    ],
  },
  {
    id: "serment-retourne",
    titre: "The daily oath — what I made of it",
    lignes: [
      "\"God told me: if I do not waste my energy, everything I conceive will come to pass.\" I waste my energy every day. So nothing comes to pass, and that is exactly consistent.",
      "\"He told me to go to the mountain.\" I do not go.",
      "\"He told me to recite Psalm 24 before sleeping.\" I do not recite it.",
      "\"He told me to speak to Him.\" I do not speak to Him.",
      "\"He told me to keep my room clean.\" It is not.",
      "Four instructions. Received from His mouth. Zero kept.",
      "\"Those who stand before you will be My concern.\" He took His side of the covenant. I did not take mine.",
      "\"If you really believed in God, you would do exactly what He told you to do.\" I do not do it. The conclusion is written inside the sentence.",
      "\"You say you hate hypocrisy more than anything. Here is yours — it is in your hand.\" It is still there today.",
      "I recite the oath in the morning, and I betray it before noon.",
    ],
  },
  {
    id: "binaire-reponses",
    titre: "The binary questions — my real answers",
    lignes: [
      "The question is not \"can you\". God already answered that. What remains: do I do it, yes or no.",
      "Will you pay the price — or not? I have not paid. Not one single day.",
      "Will you keep being a dog on a leash — or not? I keep going. It is my daily choice.",
      "Will you prove at every second that you are the man you think you are — or not? I prove the opposite every second.",
      "Will you hold the covenant today — or not? No. Not today, not yesterday, not last week.",
      "There is no third door — and I still chose to stay in the hallway.",
      "To every one of these questions, my answer in acts is no. Always no.",
    ],
  },
  {
    id: "objectifs-etat",
    titre: "My goals, and their real status",
    lignes: [
      "50 ultra-modern hospitals. Built to date: zero.",
      "50,000 homes given to my people. Given to date: zero.",
      "100 premium schools and a world-class university. Opened: zero.",
      "2 to 4 deep-water ports. Dug: zero.",
      "3 to 5 international airports. Out of the ground: zero.",
      "A sovereign AI company. Founded: no.",
      "A private military company in the world's top 5. Existing: no.",
      "500,000 formal, durable jobs. Created: zero.",
      "Multi-trillionaire before 30. In the bank today: the proof of the opposite.",
      "GLE 63 Coupé, Escalade, Range Rover Sport — end of 2026. Bought: zero.",
      "6'2\", 198 pounds, 10% body fat, radiant skin. Today: 5'7\", 148 pounds, acne.",
      "The land bought, the school started, the farming launched. None of it has moved.",
      "Every line of my Vision is waiting for the man I was supposed to become today. Today, I did nothing.",
      "These goals are not late. They never started.",
    ],
  },
  {
    id: "interrogatoire-reponses",
    titre: "The interrogation — the real answers",
    lignes: [
      "What I am doing right now — does it reflect a man who builds billion-dollar hospitals, ten-billion ports, fifteen-billion airports? No.",
      "The one who moves the borders of Africa and dominates globally? No.",
      "The one who controls finance, the markets, politics, natural resources? No.",
      "A master of geopolitics, firm and without pity? No.",
      "A man more important than a president or a king? No.",
      "The one who can develop an entire continent just by deciding to? I don't even decide my wake-up time.",
      "The life of a CONQUEROR? No.",
      "A man who triumphs over himself first? No. I lose against myself every day.",
      "A man who controls the consequences of every action? No. I suffer all of them.",
      "The man who said he would cut TikTok and Instagram, and give 100% of his time to his goals? No. I reinstall them.",
      "A man who resists and DELETES the urge instead of serving it? No. I serve it.",
      "A man who walks through boredom and difficulty without complaining? No.",
      "A man whose word kept to himself has never bent? It has never held for a single day.",
      "A man with a full vessel, climbing the staircase step by step? I have been frozen on the step for eight years.",
      "A man who does not talk and delivers, discovered only at the finished deed? I talk, and I deliver nothing.",
      "A man FAITHFUL TO GOD, keeping the mountain covenant intact? No.",
      "Or am I going to spend my life dreaming? That is exactly what I am doing.",
    ],
  },
];

export const MIROIR_EN_THESE =
  "I accept my current state, and every second I prove it. I never actually prove that I want what I say I want.";

export const MIROIR_EN_SORTIE =
  "Nothing will change until I change. Nothing on this list is a fate: every line is a decision I made again yesterday, and one I can make differently within the next minute.";
