// MIWA A — kreyòl ayisyen.
//
// Troisième langue de son manifeste quotidien (EN → FR → Créole). C'est sa
// langue maternelle, celle dans laquelle une phrase ne peut pas être tenue à
// distance : il ne peut pas la lire comme un texte étranger.
//
// AVERTISSEMENT : cette traduction est de moi, pas de lui. Le créole n'est pas
// ma langue. Il doit relire et corriger tout ce qui sonne faux — une phrase
// mal tournée dans sa propre langue perdrait exactement ce qu'elle doit porter.
//
// Client-safe.

import type { MiroirBloc } from "./miroir";

export const MIROIR_HT: MiroirBloc[] = [
  {
    id: "verite",
    titre: "Sa mwen ye, kounye a",
    lignes: [
      "Mwen pa menm youn nan bagay mwen di mwen vle ye yo.",
      "Mwen se yon moun ki masturbe chak jou.",
      "Mwen se yon nonm ki pa ka konsantre.",
      "Mwen se yon chen mare nan yon chèn. Mwen pa yon nonm ki gen dominyon.",
      "Mwen se yon lach.",
      "Mwen pa yon moun ou ka konte sou li, ni yon moun ou ka fè konfyans.",
      "Mwen piti epi mwen fèb. Mwen pa ta ka defann pèsonn nan lari, menm si mwen te vle.",
      "A 23 an, mwen bouke tout tan.",
      "1m70. 67 kilo. Se sa nonm reyèl la ye.",
    ],
  },
  {
    id: "consentement",
    titre: "Sa mwen pwouve chak segond",
    lignes: [
      "Mwen aksepte kote mwen ye kounye a. Epi chak segond, mwen pwouve li.",
      "Mwen pwouve mwen vle rete nan wotè sa a.",
      "Mwen pwouve mwen vle kenbe kò sa a.",
      "Mwen pwouve mwen vle kenbe figi sa a.",
      "Mwen pwouve mwen vle kenbe chalè sa a ki pa la.",
      "Mwen pwouve mwen vle kenbe vwa sa a.",
      "Mwen pwouve mwen vle kenbe lavi sa a.",
      "Mwen pa janm pwouve toutbon mwen vle sa mwen di mwen vle a.",
      "Di se pa vle. Vle se yon bagay ou pwouve, epi prèv la se yon zak.",
      "Sa mwen fè se sèl deklarasyon onèt sou sa mwen vle. Rès la se bri.",
      "Mwen pa bezwen mande tèt mwen sa mwen vle : gade sèlman sa mwen fè ak èdtan mwen yo.",
      "Jan mwen pase jounen mwen, se lis objektif reyèl mwen.",
      "Chak segond se yon vòt. Mwen vote pou m rete menm jan an.",
      "Pa fè anyen, se pa rete net : se siyen.",
      "Nonm mwen pral ye nan yon ane deja ap chwazi kounye a, segond apre segond, ak sa mwen fè la a.",
    ],
  },
  {
    id: "membres",
    titre: "Manm kò mwen — sa yo sèvi toutbon",
    lignes: [
      "Men mwen pa bati anyen nan sa mwen di, sa mwen panse, sa mwen planifye. Li sèvi pou m masturbe.",
      "Pye mwen pa mache nan laglwa. Yo mache nan pousyè, epi yo sèvi pou pote m antre nan chanm mwen pou m fè tèt mwen.",
      "Je mwen pa gade akonplisman sa mwen te planifye. Yo gade pònografi.",
      "Kò sa a, se ak men Li Li te fòme l — epi men sa mwen fè avè l.",
      "Se sa ki itilizasyon reyèl bagay Li konfye m nan. Pa itilizasyon rèv la : sa reyèl la.",
      "Yon lach. Yon vye bagay. Endiy devan Bondye, devan konfyans Li ak benediksyon Li.",
    ],
  },
  {
    id: "porno",
    titre: "Pònografi a — sa zak la pwouve toutbon",
    lignes: [
      "Mwen di kòm yon nonm mwen vle gen aksè ak fanm mwen vle yo. Ak pi bèl yo.",
      "Sa zak mwen yo pwouve mwen vle a se lòt bagay : fè tèt mwen tankou yon lach, yon vye bagay.",
      "Gade yon lòt nonm ap fè bagay ak fanm ki se objè dezi mwen an. Epi peye espektak sa a ak enèji mwen.",
      "Sa se pa dezi yon nonm. Se dezi yon espektatè.",
      "Mwen pa pran plas li. Mwen gade l pran l, epi mwen peye pou m gade.",
      "Apre sa mwen mete mizik epi mwen reve mwen gran. Mwen rele tèt mwen nonm dominyon. Pitit Bondye.",
      "Yon nonm dominyon ki fèk gade yon lòt nonm pran plas li. Menm èdtan an. Menm men an.",
      "Men tout wonn nan : pònografi a, men an, mizik la, rèv grandè a. Epi anyen nan bout la.",
      "Okenn nan fanm mwen di mwen vle yo p ap janm konnen mwen egziste, paske mwen pase tan ki ta dwe bati m nan ap gade lòt moun.",
    ],
  },
  {
    id: "vouloir",
    titre: "Mwen pa vle yo — mwen vle vle yo",
    lignes: [
      "Si mwen te vle bagay sa yo toutbon, mwen t ap fè sa ki nesesè pou m wè yo.",
      "Si mwen te vle machin yo, mwen t ap fè sa ki nesesè.",
      "Si mwen te vle bilding yo, konpayi yo, laglwa a, renome a, mwen t ap fè sa ki nesesè.",
      "Mwen pa vle yo. Mwen vle vle yo.",
      "Sa mwen renmen an se sansasyon vle a. Li pa koute anyen, li pa mande okenn zak, epi li bay prèske menm plezi a.",
      "Yon dezi mwen pa peye se pa yon dezi. Se yon amizman.",
      "Yon nonm ki vle yon bagay toutbon, ou rekonèt li nan sa li sakrifye. Mwen pa sakrifye anyen.",
      "Mwen konfonn emosyon vle a ak desizyon fè a.",
      "Toutotan vle rete gratis, mwen pral kontinye vle, epi mwen p ap janm gen anyen.",
    ],
  },
  {
    id: "achats",
    titre: "Sa mwen achte epi mwen pa janm louvri",
    lignes: [
      "Mwen te kòmande asid egzfolyan an sou Amazon. Li lakay mwen. Mwen pa itilize l depi plizyè mwa.",
      "Mwen te achte pomad pou wave yo, durag la. Yo la. Yo pa sèvi.",
      "Mwen te achte band pou blanchi dan yo — trant minit sou dan an. Yo pa janm louvri.",
      "Achte a te ban m sansasyon mwen t ap aji. Se egzakteman la aksyon an kanpe.",
      "Sa yo se pa objè ki poze nan yon chanm. Se volonte m, disiplin mwen ak zak mwen, poze sou yon etajè.",
      "Se pa menm pwodwi a ki manke m. Li deja peye, li deja la, a yon mèt de mwen.",
      "Dan mwen jòn paske mwen chwazi sa, se pa paske mwen manke anyen. Trant minit separe m ak dan pwòp, epi yo gratis.",
      "Ant mwen ak yon po pwòp pa gen ni lajan, ni tan, ni konesans. Gen sèlman zak la.",
    ],
  },
  {
    id: "question",
    titre: "Kesyon an — ak vrè repons lan",
    lignes: [
      "Èske yè reprezante sa mwen vle ?",
      "Èske semèn pase a reprezante sa mwen vle ?",
      "Èske jodi a reprezante sa mwen vle ?",
      "Èske minit sa a menm reprezante sa mwen vle ?",
      "Repons lan se non. Epoutan, se sa mwen chwazi — èdtan apre èdtan.",
      "Donk : mwen pa vle yon po klere. Mwen pa vle akonplisman ki depase moun. Mwen pa vle anyen nan sa.",
      "Sa mwen vle a se sa mwen fè a. Pa gen okenn lòt definisyon, epi okenn tribinal p ap aksepte yon lòt.",
      "Sèl fason pou m chanje repons mwen se chanje èdtan k ap vini an. Se pa ane a : se èdtan an.",
    ],
  },
  {
    id: "limites",
    titre: "Mwen pa menm ranpli ti lavi sa a",
    lignes: [
      "Mwen pa ap chèche konnen limit mwen. Mwen pa menm ranpli ti lavi medyòk sa a mwen ye ladan l lan.",
      "Mwen pa menm rive nan bout sa lavi mwen genyen kounye a deja pèmèt.",
      "Mwen pale sou depase moun, epi mwen pa menm okipe venn-kat èdtan mwen genyen yo.",
      "Mwen pa touche okenn plafon. Mwen pa janm menm pwoche yon sèl plafon.",
      "Pèsonn pa ka konnen sa mwen kapab fè : mwen pa janm mennen anyen jouk nan bout, menm yon ti bagay.",
      "Medyokrite mwen an menm pa ranpli. Li a mwatye vid.",
      "Mwen pa konnen limit mwen paske mwen pa janm rive jouk kote yo ye a.",
      "Mwen reve gwo bagay depi nan yon kabann mwen pa menm ranje.",
      "Anvan m vle depase limit mwen, fòk mwen ta rive nan bò ti espas sa a dabò.",
      "Ti kras mwen genyen an, mwen pa sèvi avè l. Epi mwen gen kran mande plis.",
    ],
  },
  {
    id: "preuves",
    titre: "Prèv yo — pa gen okenn",
    lignes: [
      "Pa gen okenn prèv sou entelijans mwen.",
      "Pa gen okenn prèv sou travay mwen.",
      "Pa gen okenn prèv sou grandè mwen.",
      "Uit ane. Pa gen yon sèl pwojè ki ap mache. Pa youn.",
      "Mwen pa akonpli okenn nan objektif mwen yo. Pa youn.",
      "Pèsonn — ni Bondye, ni yon zanj, ni yon obsèvatè envizib — pa ta ka devine objektif mwen yo lè l gade jan mwen viv. Se enposib.",
      "Sitiyasyon finansye mwen se mezi egzak medyokrite mwen.",
      "Kò mwen, figi mwen, chalè mwen : menm mezi a.",
    ],
  },
  {
    id: "parole",
    titre: "Pawòl mwen — chak objektif trayi",
    lignes: [
      "Mwen pa janm kenbe yon sèl jou disiplin. Pa youn.",
      "Chak objektif mwen te bay tèt mwen, mwen trayi l.",
      "Leve a senkè : trayi.",
      "Retansyon an : trayi.",
      "Zewo TikTok : mwen reenstale app la epi mwen reaktive kont lan chak jou.",
      "Mwen ale sou X tankou yon chen.",
      "Mwen pa ka chita sou yon chèz epi travay kat èdtan san kanpe.",
      "Mwen pa ka sispann reve nan tèt mwen tout lajounen.",
      "Mwen pa monte nan mòn nan.",
      "Mwen ap chèche atansyon fi yo nan yon fason dezespere.",
      "Mwen pa kenbe èdtan meditasyon mwen yo.",
      "Mwen pa kenbe seyans deep work mwen yo.",
      "Mwen vle fè lajan sou YouTube epi mwen pa menm pibliye yon sèl videyo. Se tout dosye a.",
    ],
  },
  {
    id: "reverie",
    titre: "Sèn mwen ap rejwe olye pou m viv",
    lignes: [
      "Mwen rejwe menm sèn yo san rete : entèvyou a, siksè ki deja fèt la, sajès mwen ap bay la.",
      "Nan sèn sa yo, mwen ofri yon sajès ak yon entelijans ki pa egziste ditou.",
      "Mwen konsome rezilta a nan imajinasyon m — epi apre, mwen pa grangou ase pou m bati l.",
      "Epi si mwen kontinye konsa, sa p ap janm rive. A 200%.",
      "Mwen pa refize sispann rèv konpilsif yo : mwen pa menm deside sispann yo.",
      "Mwen pa deside sispann imajine, senpleman pou kenbe lespri m kalm epi fè travay la.",
      "Reve entèvyou a koute m entèvyou a.",
      "Chak sèn mwen rejwe se yon avans mwen pran sou yon laglwa mwen p ap janm peye.",
      "Nonm nan sèn mantal mwen yo te fè travay la. Mwen menm, mwen gade l fè l.",
    ],
  },
  {
    id: "apparence",
    titre: "Figi a ak kò a, san filtè",
    lignes: [
      "1m70. 67 kilo. Fèb. Se sa nonm reyèl la ye, mezire.",
      "Yon figi ki pa swaye, plen bouton.",
      "Dan jòn.",
      "Okenn pafen. Anyen ki rete lè mwen pati.",
      "Okenn chalè. Okenn prezans.",
      "Anba mwayèn nan sou prèske tout sa ki parèt.",
      "Envizib. Ki pa vo anyen. Ki repouse moun.",
      "Mwen travèse yon chanm san pèsonn pa wè m, epi se egzakteman sa mwen bati.",
      "Anyen nan sa se pa yon aksidan. Chak liy se yon zak mwen pa poze.",
    ],
  },
  {
    id: "corps",
    titre: "Kò a — senk ane pou anyen",
    lignes: [
      "Senk ane nan gym, epi mwen sanble ak yon vye bagay.",
      "Mwen pa respekte pwogram nan.",
      "Mwen pa leve fè.",
      "Mwen pa gen okenn disiplin sou nitrisyon apre seyans lan.",
      "Chak jou, mwen retounen nan gazez.",
      "Objektif gym : echwe. Senk ane prèv.",
    ],
  },
  {
    id: "ecart",
    titre: "Espas ant rèv la ak zak la",
    lignes: [
      "Mwen reve triyon epi mwen pa menm fè sa yon nonm k ap fè mil dola fè.",
      "Mwen reve milyon sou YouTube san mwen pa bay efò moun k ap fè mil yo bay.",
      "Mwen vle pibliye sou App Store pou milya, epi mwen depanse kredi Claude mwen — yon plan 200 dola — pou m ale sou X.",
      "Mwen chèche bagay fasil yo. Epi menm sa yo, mwen pa fè yo.",
      "Epi apre sa mwen pèmèt tèt mwen kritike.",
      "Mwen toujou ap chèche yon chapant pou m evite travay mwen konnen ki nesesè pou evolisyon mwen.",
      "Kòmsi YouTube ta pral kreye videyo yo pou mwen, pibliye yo pou mwen, epi peye mwen.",
    ],
  },
  {
    id: "outils",
    titre: "Zouti mwen abandone yo",
    lignes: [
      "Mwen te enprime yon fèy pou m tcheke objektif mwen yo. Mwen pa itilize l yon sèl fwa.",
      "Mwen te mete yon sistèm imel otomatik. Mwen pa louvri yo.",
      "Mwen gen liv yo. Mwen pa li yo.",
      "Mwen pa fè absoliman anyen nan sa mwen di mwen pral fè.",
    ],
  },
  {
    id: "evitement",
    titre: "Evite travay la lè m ap bati zouti",
    lignes: [
      "Mwen bati zouti yo pou m pa oblije sèvi ak yo.",
      "Mwen bati yon app, yon liv 587 paj, 2 000 sitasyon, yon sistèm imel otomatik. Mwen pa louvri yon sèl nan imel sa yo.",
      "Ajoute yon fonksyon anplis ban m sansasyon m ap avanse. Se vèsyon sofistike pwokrastinasyon an.",
      "Lè yon sistèm pare pou m suiv li, mwen pito chanje l pase suiv li.",
      "Mwen pase plis tan ap regle kontè a pase fè bagay li konte a.",
      "Chak nouvo lide rive egzakteman lè li lè pou m egzekite ansyen an.",
      "Mwen mande pou yo bati yon sistèm disiplin pou mwen, epi mwen pa gen disiplin pou m sèvi avè l.",
      "Prepare se toujou yon fason pou pa kòmanse.",
    ],
  },
  {
    id: "lucidite",
    titre: "Sa mwen deja konnen — epi ki pa chanje anyen",
    lignes: [
      "Mwen konnen tout sa. Se mwen menm ki ekri l.",
      "Pwoblèm mwen se pa inyorans. Mwen pa gen anyen ankò pou m aprann anvan m aji.",
      "Pa gen enfòmasyon ki manke m. Pa gen zouti ki manke m. Pa gen sistèm ki manke m.",
      "Mwen konnen lwa veso a pa kè — se mwen ki ekri l — epi mwen pa aplike l.",
      "Wè medyokrite mwen klè pa korije l. Sa jis fè l pi wont.",
      "Konprann se pa fè. Ekri se pa fè. Li se pa fè.",
      "Chak jou mwen pa chanje anyen se yon vòt pou nonm mwen deja ye a.",
    ],
  },
  {
    id: "temps",
    titre: "Sa k ap rive si anyen pa chanje",
    lignes: [
      "Mwen gaspiye tan mwen chak jou, epi mwen toujou panse mwen pral rive nan objektif mwen yo.",
      "Mwen trete demen tankou jou mèveye a kote medyokrite mwen ap disparèt pou kont li.",
      "Mwen kontinye reve pandan ane yo ap pase epi y ap pwouve m kontrè a.",
      "Epi l ap konsa demen.",
      "Konsa nan yon semèn.",
      "Konsa nan yon mwa. Nan sis mwa.",
      "Konsa nan yon ane. Nan dezan.",
      "Mwa pwochen an ap egzakteman menm jan an.",
      "Fen ane a ap egzakteman menm jan an.",
      "Ane k ap vini an tou. Apre sa 25 an. Apre sa 30. Apre sa 40.",
      "Toutotan mwen rete konsa, anyen p ap chanje, epi ane yo pral kontinye pase.",
    ],
  },

  // ——— Seksyon II : pawòl li yo, vire kont li ———
  {
    id: "refus",
    titre: "Nonm mwen refize ye a — epi ki se mwen egzakteman",
    lignes: [
      "Nonm mwen refize ye a se, mo pou mo, nonm mwen ye a.",
      "Yon moun ki masturbe san kontwòl. Yon nonm san mèt. Yon chen mare ki mennen pa dezi. Se mwen.",
      "Yon lach. Yon moun ki pa vo anyen. Yon nonm òdinè, ki ka ranplase, ki ka bliye. Se mwen.",
      "Yon moun k ap reve epi k ap fè tèt li sou pwòp avni l olye pou l bati l. Se mwen.",
      "Yon anperè nan panse, yon esklav nan pratik. Se mwen.",
      "Mwen di mwen pral deplase fwontyè Afrik, epi mwen pa menm kontwole men mwen.",
      "Mwen vle domine mache ak nasyon, epi yon notifikasyon domine mwen.",
      "Moun tout moun ap pale de li a ? Pèsonn pa pale de mwen. Pèsonn pa konnen mwen egziste.",
      "Bondye pale avè m sou yon mòn — epi mwen reponn Li nan yon mouchwa.",
      "Mwen gaspiye sa Li konfye m, epi mwen gen kran mande plis.",
      "Dis ane. Anyen. Zewo. Epi mwen kwè mwen prese jodi a.",
      "Mwen pa yon wa. Mwen se yon chen k ap reve li se yon wa.",
    ],
  },
  {
    id: "phrases-retournees",
    titre: "Pwòp pawòl mwen yo, vire kont mwen",
    lignes: [
      "« Mwen pa ale sou TikTok. » Mwen reenstale app la epi mwen reaktive kont lan chak jou.",
      "« Mwen se moun tout moun ap pale de li, epi ki pa janm fennen. » Pèsonn pa pale de mwen.",
      "« Mwen se moun k ap fè tout sa. Pa nan 5 minit. KOUNYE A. » Mwen pa fè l okenn nan jou mwen te di l yo.",
      "« Every action has consequences. » Mwen viv kòmsi pa gen youn ki gen konsekans.",
      "« Chak zak se yon echanj. Kalkile sa w pran ak sa w bay. » Mwen pa janm fè kalkil la yon sèl fwa.",
      "« Chak zak se yon pak. Ak kilès ou fèk siyen ? » Mwen siyen chak jou, epi mwen konnen ak kilès.",
      "« Every yes is a thousand no. » Mwen di wi ak tout sa k ap detwi m.",
      "« Only God and you can stop you. » Bondye pa kanpe m. Donk se mwen menm sèl ki rete.",
      "« Pa gen okenn eskiz ki rete pou ou. Sèlman ou menm. » Mwen pa gen pèsonn ankò pou m akize, epi mwen toujou pa aji.",
      "« God kept His word. Now keep yours. » Li kenbe pa Li a. Mwen pa kenbe pa mwen an yon sèl jou.",
      "« A dog with a dream is still a dog. » Mwen se chen an. Rèv la entak, mwen menm non.",
      "« Ten years. Zero receipts. » Se liy mwen. Se sou tèt mwen mwen ekri l.",
      "« You'll either be the story or the audience. » Mwen se piblik la. Mwen gade lòt moun ap fè istwa a.",
      "« Nobody is coming. That's the whole point. » Pèsonn pa vini. Pèsonn p ap vini.",
      "« Se pou L jije m pou awogans pouvwa Li ban mwen an — pa janm paske m antere l. » Mwen antere l. Se egzakteman jijman mwen te di mwen refize a.",
      "« Se pou L jije m konkeran, pa janm lach. » L ap jije m lach, epi L ap gen prèv yo.",
      "« Kò mwen, se ak men Li Li fòme l. » Epi men sa mwen fè avè l.",
      "« Mwen refize se yon lach, yon moun k ap masturbe, yon moun soumèt. » Mwen se tou lè twa, jodi a menm.",
      "« Si w vle bati yo toutbon, respekte men w. » Mwen pa respekte l. Donk mwen pa vle bati yo.",
      "« Si w vle wè yo toutbon, respekte je w. » Mwen pa respekte yo. Donk mwen pa vle wè yo.",
      "« Pa gen twazyèm pòt. » Mwen pase uit ane ap chèche youn.",
      "« Priye san rete. » Mwen pa priye.",
      "« Bondye se sous mwen, pwovizyon Li san limit, anyen pa enposib pou Bondye. » Mwen pa mande L anyen, epi mwen pa fè anyen.",
      "« Enbranlab. Demezire. Fidèl. » Mwen plwaye chak jou, mwen pa pwodui anyen, epi mwen pa kenbe anyen.",
      "« Mwen pa pale, mwen pa deba, mwen pa bay opinyon. Mwen FÈ. Mwen AJI. » Mwen pale, mwen deba, mwen bay opinyon. Mwen pa fè anyen.",
      "« Mwen se eritye Bondye. Mwen refize se yon moun ki pa vo anyen. » Jodi a, mwen se egzakteman sa mwen refize a.",
    ],
  },
  {
    id: "serment-retourne",
    titre: "Sèman jounen an — sa mwen fè avè l",
    lignes: [
      "« Bondye di m : si mwen pa gaspiye enèji mwen, tout sa mwen konsevwa ap reyalize. » Mwen gaspiye enèji mwen chak jou. Donk anyen pa reyalize, epi sa kòrèk nèt.",
      "« Li di m monte nan mòn nan. » Mwen pa monte.",
      "« Li di m resite Sòm 24 anvan m dòmi. » Mwen pa resite l.",
      "« Li di m pale avè L. » Mwen pa pale avè L.",
      "« Li di m kenbe chanm mwen pwòp. » Li pa pwòp.",
      "Kat konsiy. Resevwa nan bouch Li. Zewo kenbe.",
      "« Moun k ap kanpe devan ou, se afè pa M. » Li pran pati pa L nan kontra a. Mwen pa pran pati pa m.",
      "« If you really believed in God, you would do exactly what He told you to do. » Mwen pa fè l. Konklizyon an ekri nan fraz la menm.",
      "« Ou di ou rayi ipokrizi plis pase tout bagay. Men pa w la, li nan men w. » Li toujou la jodi a.",
      "Mwen resite sèman an nan maten, epi mwen trayi l anvan midi.",
    ],
  },
  {
    id: "binaire-reponses",
    titre: "Kesyon binè yo — vrè repons mwen yo",
    lignes: [
      "Kesyon an se pa « èske ou kapab ». Bondye deja reponn sa. Sa ki rete : èske mwen fè l, wi ou non.",
      "Will you pay the price — or not ? Mwen pa peye. Pa yon sèl jou.",
      "Will you keep being a dog on a leash — or not ? Mwen kontinye. Se chwa mwen chak jou.",
      "Will you prove at every second that you are the man you think you are — or not ? Mwen pwouve kontrè a chak segond.",
      "Will you hold the covenant today — or not ? Non. Ni jodi a, ni yè, ni semèn pase.",
      "Pa gen twazyèm pòt — epi mwen toujou chwazi rete nan koulwa a.",
      "Pou chak nan kesyon sa yo, repons mwen nan zak se non. Toujou non.",
    ],
  },
  {
    id: "objectifs-etat",
    titre: "Objektif mwen yo, ak kote yo ye toutbon",
    lignes: [
      "50 lopital iltramodèn. Bati jiska jodi a : zewo.",
      "50 000 kay bay pèp mwen. Bay jiska jodi a : zewo.",
      "100 lekòl premyòm ak yon inivèsite nan nivo mondyal. Louvri : zewo.",
      "2 a 4 pò dlo fon. Fouye : zewo.",
      "3 a 5 ayewopò entènasyonal. Soti nan tè a : zewo.",
      "Yon konpayi IA souvren. Fonde : non.",
      "Yon konpayi militè prive nan top 5 mondyal. Egziste : non.",
      "500 000 travay fòmèl ki dire. Kreye : zewo.",
      "Multi-triyonè anvan 30 an. Nan bank lan jodi a : prèv kontrè a.",
      "GLE 63 Coupé, Escalade, Range Rover Sport — fen 2026. Achte : zewo.",
      "1m88, 90 kilo, 10% grès, po klere. Jodi a : 1m70, 67 kilo, bouton.",
      "Tè a achte, lekòl la kòmanse, agrikilti a lanse. Anyen nan sa pa bouje.",
      "Chak liy nan Vizyon mwen ap tann nonm mwen te dwe vin ye jodi a. Jodi a, mwen pa fè anyen.",
      "Objektif sa yo pa an reta. Yo pa janm kòmanse.",
    ],
  },
  {
    id: "interrogatoire-reponses",
    titre: "Entèwogatwa a — vrè repons yo",
    lignes: [
      "Sa mwen ap fè la a — èske sa reflete yon nonm k ap bati lopital a 1 milya, pò a 10 milya, ayewopò a 15 milya ? Non.",
      "Moun k ap deplase fwontyè Afrik epi k ap domine mondyalman an ? Non.",
      "Moun k ap kontwole finans, labous, politik, resous natirèl yo ? Non.",
      "Yon mèt nan jeopolitik, fèm epi san pitye ? Non.",
      "Yon nonm ki pi enpòtan pase yon prezidan oswa yon wa ? Non.",
      "Moun ki ka devlope yon kontinan antye jis paske li deside sa ? Mwen pa menm deside a ki lè m leve.",
      "Lavi yon KONKERAN ? Non.",
      "Yon nonm ki venk tèt li anvan tout bagay ? Non. Mwen pèdi kont tèt mwen chak jou.",
      "Yon nonm ki kontwole konsekans chak zak ? Non. Mwen sibi yo tout.",
      "Nonm ki te di l ap koupe TikTok ak Instagram, epi ki bay 100% tan l ak objektif li ? Non. Mwen reenstale yo.",
      "Yon nonm ki reziste epi ki SIPRIME anvi a, olye pou l sèvi l ? Non. Mwen sèvi l.",
      "Yon nonm ki mache nan raz ak difikilte san plenyen ? Non.",
      "Yon nonm ki pawòl li bay tèt li pa janm plwaye ? Li pa janm kenbe yon sèl jou.",
      "Yon nonm ak veso plen, k ap monte eskalye a mach apre mach ? Mwen bloke sou mach la depi uit ane.",
      "Yon nonm ki pa pale epi ki livre, ke yo dekouvri sèlman lè bagay la fin fèt ? Mwen pale, epi mwen pa livre anyen.",
      "Yon nonm FIDÈL AK BONDYE, ki kenbe alyans mòn nan entak ? Non.",
      "Oswa mwen pral pase lavi m ap reve ? Se egzakteman sa mwen ap fè.",
    ],
  },
];

export const MIROIR_HT_THESE =
  "Mwen aksepte kote mwen ye kounye a, epi chak segond mwen pwouve li. Mwen pa janm pwouve toutbon mwen vle sa mwen di mwen vle a.";

export const MIROIR_HT_SORTIE =
  "Anyen p ap chanje toutotan mwen pa chanje. Anyen nan lis sa a se pa yon desten : chak liy se yon desizyon mwen te repran yè, epi mwen ka repran l yon lòt jan nan minit k ap vini an.";
