// AUTO-GENERATED by scripts/parse-vaisseau.mjs — do not edit by hand.
export interface ChapterMeta { n: number; book: string; title: string; }
export const CHAPTER_META: ChapterMeta[] = [
  {
    "n": 1,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La loi du vaisseau"
  },
  {
    "n": 2,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "L'homme plein qui doute reçoit plus que l'homme vide qui croit"
  },
  {
    "n": 3,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Conscience = présence du divin"
  },
  {
    "n": 4,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Le mécanisme limbique contre le préfrontal"
  },
  {
    "n": 5,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La spirale descendante"
  },
  {
    "n": 6,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Le voyeurisme comme dispersion structurelle"
  },
  {
    "n": 7,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Le goon maxing — extraction par stimulation sans complétion"
  },
  {
    "n": 8,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Pornographie et masturbation compulsive — la destruction du vaisseau"
  },
  {
    "n": 9,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Les entités, les archontes, et le lieu où tu dors"
  },
  {
    "n": 10,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "L'architecture des plateformes"
  },
  {
    "n": 11,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "TikTok, Instagram, le scrolling — les fermes énergétiques modernes"
  },
  {
    "n": 12,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La consommation invisible"
  },
  {
    "n": 13,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "L'énergie sexuelle comme force créatrice primaire"
  },
  {
    "n": 14,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La transmutation"
  },
  {
    "n": 15,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Le courant alterné — faire de ton corps une antenne"
  },
  {
    "n": 16,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La méditation — matin et soir, l'antenne qui s'accorde"
  },
  {
    "n": 17,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Les trois plans : physique, mental, spirituel"
  },
  {
    "n": 18,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Friction, incarnation, direction"
  },
  {
    "n": 19,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Le protocole en quatre mouvements"
  },
  {
    "n": 20,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La contre-attaque des 24 heures et les trois semaines de bascule"
  },
  {
    "n": 21,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "La honte est le carburant — le piège du consentement"
  },
  {
    "n": 22,
    "book": "Livre I · L'énergie : le vaisseau avant la grâce",
    "title": "Recovery vs Recognition — tu n'es pas malade, tu te souviens"
  },
  {
    "n": 23,
    "book": "Livre II · Les paroles reçues",
    "title": "La provision bloquée — pourquoi l'immoral sexuel ne peut pas s'enrichir"
  },
  {
    "n": 24,
    "book": "Livre II · Les paroles reçues",
    "title": "La semence comme monnaie spirituelle — celui qui a, on lui donnera"
  },
  {
    "n": 25,
    "book": "Livre II · Les paroles reçues",
    "title": "La bouche du serpent — par manque de connaissance, l'homme est détruit"
  },
  {
    "n": 26,
    "book": "Livre II · Les paroles reçues",
    "title": "« Tant que tu ne fais pas ce qu'ils ont dit, rien ne se débloquera »"
  },
  {
    "n": 27,
    "book": "Livre II · Les paroles reçues",
    "title": "« Si tu ne gaspilles pas ton énergie, tout ce que tu penses se réalisera »"
  },
  {
    "n": 28,
    "book": "Livre II · Les paroles reçues",
    "title": "« Ce que Dieu fait pour toi sort de Ses habitudes »"
  },
  {
    "n": 29,
    "book": "Livre II · Les paroles reçues",
    "title": "La vision de l'aigle"
  },
  {
    "n": 30,
    "book": "Livre II · Les paroles reçues",
    "title": "Renoncer aux contenus pour adultes — la protection du plan divin"
  },
  {
    "n": 31,
    "book": "Livre II · Les paroles reçues",
    "title": "Le Psaume 24 — texte intégral et opération"
  },
  {
    "n": 32,
    "book": "Livre II · Les paroles reçues",
    "title": "La montagne"
  },
  {
    "n": 33,
    "book": "Livre II · Les paroles reçues",
    "title": "Cesser de ruminer, prier à la place"
  },
  {
    "n": 34,
    "book": "Livre III · Les promesses sans conditions",
    "title": "La radicalité des paroles"
  },
  {
    "n": 35,
    "book": "Livre III · Les promesses sans conditions",
    "title": "Pourquoi les humains rabotent les promesses"
  },
  {
    "n": 36,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Tout ce que vous demanderez »"
  },
  {
    "n": 37,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« S'il lui demande un poisson, lui donnera-t-il un serpent ? » — la bonté du Père garantie"
  },
  {
    "n": 38,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Plante le grain ; Je fais pousser l'arbre » — la coopération sacrée"
  },
  {
    "n": 39,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Rien ne vous sera impossible »"
  },
  {
    "n": 40,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Sois ! Et c'est »"
  },
  {
    "n": 41,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Tu décréteras une chose »"
  },
  {
    "n": 42,
    "book": "Livre III · Les promesses sans conditions",
    "title": "Demander le plus haut — le hadith du Firdaws"
  },
  {
    "n": 43,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Je suis selon l'opinion que Mon serviteur a de Moi »"
  },
  {
    "n": 44,
    "book": "Livre III · Les promesses sans conditions",
    "title": "L'assomption de l'accompli — vivre depuis la fin"
  },
  {
    "n": 45,
    "book": "Livre III · Les promesses sans conditions",
    "title": "La parole qui décrète — la mécanique du verbe créateur"
  },
  {
    "n": 46,
    "book": "Livre III · Les promesses sans conditions",
    "title": "Pourquoi les conditions apparentes ne sont pas des conditions"
  },
  {
    "n": 47,
    "book": "Livre III · Les promesses sans conditions",
    "title": "« Quoi qu'il croie, il devient cela »"
  },
  {
    "n": 48,
    "book": "Livre III · Les promesses sans conditions",
    "title": "La grâce — la loi au-dessus de l'effort et du karma"
  },
  {
    "n": 49,
    "book": "Livre III · Les promesses sans conditions",
    "title": "Croyance et foi — la distinction qui change tout"
  },
  {
    "n": 50,
    "book": "Livre III · Les promesses sans conditions",
    "title": "Là où l'âme et le divin sont réunis"
  },
  {
    "n": 51,
    "book": "Livre III · Les promesses sans conditions",
    "title": "La dévotion à la forme — saguna upasana"
  },
  {
    "n": 52,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Tu n'auras pas d'autres dieux devant ma face"
  },
  {
    "n": 53,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Les idoles modernes"
  },
  {
    "n": 54,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Responsabilité totale, culpabilité zéro"
  },
  {
    "n": 55,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Metanoia — le retournement de l'esprit"
  },
  {
    "n": 56,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Si Dieu est pour moi, qui sera contre moi ?"
  },
  {
    "n": 57,
    "book": "Livre IV · La posture qui manifeste",
    "title": "La phrase comme arme de récusation"
  },
  {
    "n": 58,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Le silence sur les visions"
  },
  {
    "n": 59,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Le pont des incidents n'est pas ton département"
  },
  {
    "n": 60,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Effort et lâcher-prise — abhyasa et vairagya"
  },
  {
    "n": 61,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Le principe d'obliquité"
  },
  {
    "n": 62,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Ne pas mesurer le temps"
  },
  {
    "n": 63,
    "book": "Livre IV · La posture qui manifeste",
    "title": "L'infini ne connaît ni grand ni petit"
  },
  {
    "n": 64,
    "book": "Livre IV · La posture qui manifeste",
    "title": "L'erreur du grand projet — quand l'ambition fabrique la résistance"
  },
  {
    "n": 65,
    "book": "Livre IV · La posture qui manifeste",
    "title": "La galaxie et le brin d'herbe — la fiabilité unique du divin"
  },
  {
    "n": 66,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Cesser d'ajouter à l'infini — l'art de ne pas se mettre en travers"
  },
  {
    "n": 67,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Le non-jugement et la non-mesure"
  },
  {
    "n": 68,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Le piège du rabotage — comment l'ego rétrécit l'infini"
  },
  {
    "n": 69,
    "book": "Livre IV · La posture qui manifeste",
    "title": "La vraie humilité contre la fausse — l'exemple de Marie"
  },
  {
    "n": 70,
    "book": "Livre IV · La posture qui manifeste",
    "title": "L'ego qui prédit et qui contrôle"
  },
  {
    "n": 71,
    "book": "Livre IV · La posture qui manifeste",
    "title": "La connaissance qui désarme l'ego"
  },
  {
    "n": 72,
    "book": "Livre IV · La posture qui manifeste",
    "title": "L'ego comme outil"
  },
  {
    "n": 73,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Tawakkul et rida — la confiance qui accepte d'être surpris"
  },
  {
    "n": 74,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Les quantum jumps — sélectionner ta branche de réalité"
  },
  {
    "n": 75,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Pourquoi les petits choix basculent tout"
  },
  {
    "n": 76,
    "book": "Livre IV · La posture qui manifeste",
    "title": "Décider, décréter, ne pas négocier"
  },
  {
    "n": 77,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "La tyrannie des petites décisions — naissance d'un concept"
  },
  {
    "n": 78,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "L'arbre des réalités — l'image scientifique du carrefour permanent"
  },
  {
    "n": 79,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Tu n'es pas une personne, tu es un parcours qui se choisit"
  },
  {
    "n": 80,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Les micro-choix invisibles — ce que tu fais à 14h détermine où tu seras dans dix ans"
  },
  {
    "n": 81,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "L'inertie du parcours — pourquoi les choix se renforcent eux-mêmes"
  },
  {
    "n": 82,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "L'illusion du grand pivot — la transformation est moléculaire"
  },
  {
    "n": 83,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Le quantum jump — ce qui se passe vraiment au moment du saut"
  },
  {
    "n": 84,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Les deux versions de toi en superposition — la mécanique du collapse"
  },
  {
    "n": 85,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Devenir avant d'agir — l'identité du sauteur"
  },
  {
    "n": 86,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "La phrase qui change la branche"
  },
  {
    "n": 87,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Les signes de la nouvelle branche"
  },
  {
    "n": 88,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Le retour à l'ancienne branche — résister à la pesanteur de l'identité passée"
  },
  {
    "n": 89,
    "book": "Livre V · La tyrannie des petites décisions — carrefours, sauts quantiques, et lignes temporelles",
    "title": "Le carrefour reconnu — vivre avec la conscience du carrefour permanent"
  },
  {
    "n": 90,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "L'ego qui négocie — pourquoi tu rabotes même quand tu sais"
  },
  {
    "n": 91,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "L'écart entre la connaissance et l'incarnation"
  },
  {
    "n": 92,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "« Be still, and know that I am God » — la phrase de la cessation"
  },
  {
    "n": 93,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "« Ne sais-tu pas que je suis Dieu ? » — la remontrance qui détrône l'ego"
  },
  {
    "n": 94,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "« Je suis » — participer au nom divin"
  },
  {
    "n": 95,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "Participation contre substitution — la distinction qui sauve"
  },
  {
    "n": 96,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "« Que la lumière soit » — Dieu n'a pas décrété une bougie"
  },
  {
    "n": 97,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "« Ce n'est plus moi qui vis » — Paul, fanā, et l'instrument qui s'efface"
  },
  {
    "n": 98,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "L'ego comme calculateur — pourquoi il rabote toujours"
  },
  {
    "n": 99,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "L'appareil opératoire des trois phrases"
  },
  {
    "n": 100,
    "book": "Livre VI · L'ego-killer — la soumission qui ouvre le canal",
    "title": "Le canal ouvert — ce qui se passe quand l'ego s'est tu"
  },
  {
    "n": 101,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "La question qui scandalise — Asaph au Psaume 73"
  },
  {
    "n": 102,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "La loi est sans personne — pourquoi elle ne juge pas"
  },
  {
    "n": 103,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "La méprise fondamentale — confondre la loi morale et la loi de manifestation"
  },
  {
    "n": 104,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "Le criminel obéit aussi à la loi — la mécanique sans préférence"
  },
  {
    "n": 105,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "Pourquoi le bon doute et le méchant ne doute pas"
  },
  {
    "n": 106,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "La culpabilité, le mérite, et l'auto-sabotage du juste"
  },
  {
    "n": 107,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "« La pluie tombe sur les justes et sur les injustes » — la radicalité de Matthieu 5:45"
  },
  {
    "n": 108,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "L'illusion d'optique — ce qui se voit et ce qui ne se voit pas"
  },
  {
    "n": 109,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "Le compte final — la loi morale opère ailleurs"
  },
  {
    "n": 110,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "Le piège du ressentiment — l'amertume qui ferme le canal"
  },
  {
    "n": 111,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "Tirer la leçon des méchants — apprendre la loi à l'école qu'on n'aurait pas choisie"
  },
  {
    "n": 112,
    "book": "Livre VII · La loi sans partialité — pourquoi les méchants prospèrent et les bons souffrent",
    "title": "L'homme juste qui maîtrise la loi — la rare combinaison"
  },
  {
    "n": 113,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "I am a man of absolute dominion — la déclaration fondatrice"
  },
  {
    "n": 114,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Pourquoi la parole tenue à soi-même est le fondement de toute autre parole"
  },
  {
    "n": 115,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Le test de l'écoute du ciel — Dieu observe à quel point tu es sérieux"
  },
  {
    "n": 116,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Les conditions de la dominion absolue — précision, irrévocabilité, non-négociation"
  },
  {
    "n": 117,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "0 TikTok est 0 — pas 1, pas 2, pas exceptionnellement"
  },
  {
    "n": 118,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "0 dopamine — la doctrine du zéro absolu"
  },
  {
    "n": 119,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Quand je dis montagne, c'est montagne — l'exécution sans clause"
  },
  {
    "n": 120,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Quand je dis méditation, c'est méditation — l'engagement non-négociable"
  },
  {
    "n": 121,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "Mes envies ne me contrôlent pas — la souveraineté sur le limbique"
  },
  {
    "n": 122,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "La parole qui se trahit — le coût d'une seule entorse"
  },
  {
    "n": 123,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "La parole qui se tient — l'effet cumulatif d'un mois sans entorse"
  },
  {
    "n": 124,
    "book": "Livre VIII · I am a man of absolute dominion — la parole tenue à soi-même",
    "title": "L'homme qui est devenu sa parole — l'aboutissement de la dominion"
  },
  {
    "n": 125,
    "book": "Livre IX · La liturgie quotidienne",
    "title": "Le matin"
  },
  {
    "n": 126,
    "book": "Livre IX · La liturgie quotidienne",
    "title": "La journée"
  },
  {
    "n": 127,
    "book": "Livre IX · La liturgie quotidienne",
    "title": "Le soir"
  },
  {
    "n": 128,
    "book": "Livre IX · La liturgie quotidienne",
    "title": "Le carnet des phrases-armes"
  },
  {
    "n": 129,
    "book": "Livre IX · La liturgie quotidienne",
    "title": "Quand tu doutes"
  },
  {
    "n": 130,
    "book": "Épilogue",
    "title": "Tu y es"
  }
];
export const CHAPTER_TITLES: Record<number, string> = Object.fromEntries(
  CHAPTER_META.map((c) => [c.n, c.title]),
);
